# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.

File automatically generated. See the documentation to update questions/answers/hints programmatically.

Run the `initialize.py` module, then for each question you can query the
answer or an hint with `hint(n)` or `answer(n)` for `n` question number.

In [1]:
%run initialise.py

#### 1. Import the numpy package under the name `np` (★☆☆)

In [2]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [3]:
print(np.__version__)
print(np.show_config())

1.26.4
Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: /c/opt/64/include
    lib directory: /c/opt/64/lib
    name: openblas64
    openblas configuration: USE_64BITINT=1 DYNAMIC_ARCH=1 DYNAMIC_OLDER= NO_CBLAS=
      NO_LAPACK= NO_LAPACKE= NO_AFFINITY=1 USE_OPENMP= SKYLAKEX MAX_THREADS=2
    pc file directory: C:/opt/64/lib/pkgconfig
    version: 0.3.23.dev
  lapack:
    detection method: internal
    found: true
    include directory: unknown
    lib directory: unknown
    name: dep3179274605568
    openblas configuration: unknown
    pc file directory: unknown
    version: 1.26.4
Compilers:
  c:
    commands: cl
    linker: link
    name: msvc
    version: 19.29.30153
  c++:
    commands: cl
    linker: link
    name: msvc
    version: 19.29.30153
  cython:
    commands: cython
    linker: cython
    name: cython
    version: 3.0.8
Machine Information:
  build:
    cpu: x86_64
    endian: little
    family: x86_64
    system: windows


#### 3. Create a null vector of size 10 (★☆☆)

In [4]:
arr1 = np.zeros(10)
arr1

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 4. How to find the memory size of any array (★☆☆)

In [5]:
arr1.itemsize * arr1.size

80

#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [6]:
help(np.add)

Help on ufunc:

add = <ufunc 'add'>
    add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

    Add arguments element-wise.

    Parameters
    ----------
    x1, x2 : array_like
        The arrays to be added.
        If ``x1.shape != x2.shape``, they must be broadcastable to a common
        shape (which becomes the shape of the output).
    out : ndarray, None, or tuple of ndarray and None, optional
        A location into which the result is stored. If provided, it must have
        a shape that the inputs broadcast to. If not provided or None,
        a freshly-allocated array is returned. A tuple (possible only as a
        keyword argument) must have length equal to the number of outputs.
    where : array_like, optional
        This condition is broadcast over the input. At locations where the
        condition is True, the `out` array will be set to the ufunc result.
        Elsewhere, the `out` array will retai

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [7]:
arr2 = np.zeros(10)
arr2[4] = 1
arr2

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [8]:
arr3 = np.arange(10,50)
arr3

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [9]:
arr3 = arr3[::-1]
arr3

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [10]:
np.arange(9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [11]:
arr = [1,2,0,0,4,0]
np.nonzero(arr)

(array([0, 1, 4], dtype=int64),)

#### 11. Create a 3x3 identity matrix (★☆☆)

In [12]:
np.identity(3).astype('int')

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

#### 12. Create a 3x3x3 array with random values (★☆☆)

In [13]:
arr =  np.random.random((3,3,3))
arr

array([[[0.58935355, 0.23032254, 0.72607977],
        [0.72481653, 0.36722228, 0.17879813],
        [0.91556088, 0.98406314, 0.2600895 ]],

       [[0.98859926, 0.85052885, 0.23047424],
        [0.12656741, 0.67919674, 0.70029915],
        [0.61080884, 0.41569375, 0.9364184 ]],

       [[0.27556426, 0.28940844, 0.2979218 ],
        [0.05643526, 0.91511976, 0.27227055],
        [0.08383821, 0.28933213, 0.47291953]]])

#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [14]:
arr =  np.random.random((10,10))
print(arr)
print(arr.min(),arr.max())

[[0.31663146 0.9822808  0.44588519 0.00187238 0.66138615 0.10418895
  0.07596654 0.56812795 0.06761978 0.36477981]
 [0.80641022 0.05280192 0.8790919  0.72657481 0.75898127 0.52963459
  0.6767974  0.17337365 0.13180503 0.08960593]
 [0.99661476 0.4215183  0.70389453 0.94935895 0.01861658 0.05014271
  0.09626135 0.50997741 0.01964753 0.05965071]
 [0.21463408 0.14846126 0.2654648  0.3130702  0.30620101 0.34760326
  0.47578808 0.62113287 0.5659528  0.99067902]
 [0.16247237 0.37675357 0.19801474 0.53524161 0.53344471 0.65668458
  0.26003713 0.60563878 0.70242886 0.40937727]
 [0.37970603 0.69391558 0.29864321 0.31245349 0.10876426 0.18732516
  0.21706846 0.70512001 0.2404149  0.14533444]
 [0.49323461 0.41944476 0.34210953 0.77652746 0.10919864 0.16204936
  0.52548233 0.06542619 0.86717918 0.1988514 ]
 [0.50863938 0.17178795 0.83640197 0.12244252 0.63030119 0.3991214
  0.41200252 0.40682183 0.2719006  0.54897147]
 [0.21207531 0.03896262 0.05135457 0.54743381 0.59998407 0.64265964
  0.30370436 

#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [15]:
arr = np.random.random(30)
arr.mean()

0.6287626888144291

#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [16]:
# 1st approach
# arr = np.zeros(36).reshape((6,6))
# arr[:1] = arr[-1:] = arr[:,-1:] = arr[:,:1] = 1

# 2nd approach
arr = np.ones(36).reshape((6,6))
arr[1:-1,1:-1] = 0
arr

array([[1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1.]])

#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [17]:
arr = np.ones(36).reshape((6,6))
arr[:1] = arr[-1:] = arr[:,-1:] = arr[:,:1] = 0
arr

array([[0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0.]])

#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [18]:
0 * np.nan

nan

In [19]:
np.nan == np.nan

False

In [20]:
np.inf > np.nan

False

In [21]:
np.nan - np.nan

nan

In [22]:
np.nan in set([np.nan])

True

In [23]:
0.3 == 3 * 0.1

False

In [24]:
3*0.1

0.30000000000000004

#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [25]:
# arr = np.zeros(25).reshape((5,5))
# i=1
# j=0
# while(i<5):
#     arr[i][j] = i
#     i+=1
#     j+=1
# arr
Z = np.diag(1+np.arange(4),k=-1)
print(Z)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [26]:
# arr = np.arange(64).reshape((8,8))
# np.where(arr%2==0, 1,0)

arr = np.zeros((8,8),dtype=int)
arr[1::2,::2] = arr[::2,1::2] = 1
arr

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)

In [27]:
np.unravel_index(99,(6,7,8))

(1, 5, 3)

#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [28]:
arr = np.array([[0,1],[1,0]])
np.tile(arr,(4,4))

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

#### 22. Normalize a 5x5 random matrix (★☆☆)

In [29]:
arr = np.random.random((5,5))
(arr - arr.mean())/(arr.std())

array([[-1.83012959,  1.32638349,  0.9242287 , -0.61856022, -0.91470444],
       [ 0.01020094, -0.5464682 ,  0.28582245,  0.55162326, -1.35136706],
       [ 0.8927095 , -0.65892177, -0.41087608,  0.17378864, -0.59492802],
       [-0.80895713,  1.37544147,  1.28359347, -0.50904591, -1.208683  ],
       [ 1.27402735,  1.20548962,  0.90472368,  0.9316492 , -1.68704033]])

#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [30]:
color = np.dtype([("r", np.ubyte),
                  ("g", np.ubyte),
                  ("b", np.ubyte),
                  ("a", np.ubyte)])
print(type(color))

<class 'numpy.dtypes.VoidDType'>


#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [31]:
a = np.arange(5*3).reshape((5,3))
b = np.arange(3*2).reshape((3,2))
# print(a,b)
a.dot(b)

array([[ 10,  13],
       [ 28,  40],
       [ 46,  67],
       [ 64,  94],
       [ 82, 121]])

#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [32]:
arr = np.arange(12)
arr[(arr>=3) & (arr<=8)] *= -1
arr

array([ 0,  1,  2, -3, -4, -5, -6, -7, -8,  9, 10, 11])

#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [33]:
print(help(sum))
from numpy import *
print(help(sum))

Help on built-in function sum in module builtins:

sum(iterable, /, start=0)
    Return the sum of a 'start' value (default: 0) plus an iterable of numbers

    When the iterable is empty, return the start value.
    This function is intended specifically for use with numeric values and may
    reject non-numeric types.

None
Help on _ArrayFunctionDispatcher in module numpy:

sum(a, axis=None, dtype=None, out=None, keepdims=<no value>, initial=<no value>, where=<no value>)
    Sum of array elements over a given axis.

    Parameters
    ----------
    a : array_like
        Elements to sum.
    axis : None or int or tuple of ints, optional
        Axis or axes along which a sum is performed.  The default,
        axis=None, will sum all of the elements of the input array.  If
        axis is negative it counts from the last to the first axis.

        .. versionadded:: 1.7.0

        If axis is a tuple of ints, a sum is performed on all of the axes
        specified in the tuple instea

In [34]:
sum(range(5),initial=-1)

9

#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [35]:
Z = np.arange(10)
print(Z)
print(Z**Z)
print(2 << Z,2 << Z >> 2)
print(Z < -Z)
print(1j*Z)
print(Z/1/1)
# print(Z<Z>)  #invalid

[0 1 2 3 4 5 6 7 8 9]
[        1         1         4        27       256      3125     46656
    823543  16777216 387420489]
[   2    4    8   16   32   64  128  256  512 1024] [  0   1   2   4   8  16  32  64 128 256]
[False False False False False False False False False False]
[0.+0.j 0.+1.j 0.+2.j 0.+3.j 0.+4.j 0.+5.j 0.+6.j 0.+7.j 0.+8.j 0.+9.j]
[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


#### 28. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [36]:
print(np.array(0) / np.array(0),
np.array(0) // np.array(0),
np.array([np.nan]).astype(int).astype(float))

nan 0 [-2.14748365e+09]


C:\Users\prashant\AppData\Local\Temp\ipykernel_10276\2861961488.py:1: RuntimeWarning: invalid value encountered in divide
  print(np.array(0) / np.array(0),
C:\Users\prashant\AppData\Local\Temp\ipykernel_10276\2861961488.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  np.array(0) // np.array(0),
C:\Users\prashant\AppData\Local\Temp\ipykernel_10276\2861961488.py:3: RuntimeWarning: invalid value encountered in cast
  np.array([np.nan]).astype(int).astype(float))


#### 29. How to round away from zero a float array ? (★☆☆)

In [37]:
Z = np.random.uniform(-10,+10,100)
print(np.copysign(np.ceil(np.abs(Z)), Z))

# More readable but less efficient
# print(np.where(Z>0, np.ceil(Z), np.floor(Z)))

[ -8.  -8.  -5.  -3.   5.  -8.  -8.   7.   9. -10.  -3.   9.   8. -10.
 -10.   5.   5. -10.  -2.  -7.   3.  -6.   2.   4.   3.   3.   2.   4.
  -1.  -6.  -2.   7.  -5.  -3.  -3.   6.   9.  -8.  -5.   8.  -4.   8.
   7.   1.  -7.  -9.   1. -10.   5.  -6.  -3. -10.   3.  -8.  -7.   7.
  -5.   7.  -7.  -5.  -4.   6.   8.  -9.  -1.  10.   1.  -3.   1.   2.
  -6.  -9.  -4.  -5.  -7.   9.  -1.  -1.   1.  -6.   5.   7.   4.  -6.
  -2.   6.   2.   7.  -5.  -6.   1. -10.   6.  -5.   2.  -5.   5.  -1.
  -6.  -8.]


#### 30. How to find common values between two arrays? (★☆☆)

In [38]:
Z1 = np.random.randint(0,10,10)
Z2 = np.random.randint(0,10,10)
print(np.intersect1d(Z1,Z2))
print(Z1,Z2)

[2 3 4 5]
[1 3 5 2 2 4 1 5 5 5] [0 2 0 5 0 5 6 3 7 4]


#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [39]:
# Suicide mode on
defaults = np.seterr(all="ignore")
Z = np.ones(1) / 0

# Back to sanity
_ = np.seterr(**defaults)

# Equivalently with a context manager
with np.errstate(all="ignore"):
    np.arange(3) / 0

#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [40]:
np.sqrt(-1)

C:\Users\prashant\AppData\Local\Temp\ipykernel_10276\3438155168.py:1: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(-1)


nan

In [41]:
np.emath.sqrt(-1)

1j

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [42]:
import datetime
help(datetime)

Help on module datetime:

NAME
    datetime - Fast implementation of the datetime type.

MODULE REFERENCE
    https://docs.python.org/3.12/library/datetime.html

    The following documentation is automatically generated from the Python
    source files.  It may be incomplete, incorrect or include features that
    are considered implementation detail and may vary between Python
    implementations.  When in doubt, consult the module reference at the
    location listed above.

CLASSES
    builtins.object
        date
            datetime
        time
        timedelta
        tzinfo
            timezone

    class date(builtins.object)
     |  date(year, month, day) --> date object
     |
     |  Methods defined here:
     |
     |  __add__(self, value, /)
     |      Return self+value.
     |
     |  __eq__(self, value, /)
     |      Return self==value.
     |
     |  __format__(...)
     |      Formats self with strftime.
     |
     |  __ge__(self, value, /)
     |      Return sel

In [43]:
yesterday = np.datetime64('today') - np.timedelta64(1)
today     = np.datetime64('today')
tomorrow  = np.datetime64('today') + np.timedelta64(1)
print(yesterday, today, tomorrow)

2024-03-04 2024-03-05 2024-03-06


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [44]:
Z = np.arange('2016-07', '2016-08', dtype='datetime64[D]')
print(Z)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

In [45]:
A = np.ones(3)*1
B = np.ones(3)*2
np.add(A,B,out=B)
np.divide(A,2,out=A)
np.negative(A,out=A)
np.multiply(A,B,out=A)

array([-1.5, -1.5, -1.5])

#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

In [46]:
arr = np.linspace(0,5,10)
print(arr)
print(arr.astype('int'))
print(np.floor(arr))
print((arr*10)//10)
Z=arr
print(Z - Z%1)
print(Z // 1)
print(np.trunc(Z))

[0.         0.55555556 1.11111111 1.66666667 2.22222222 2.77777778
 3.33333333 3.88888889 4.44444444 5.        ]
[0 0 1 1 2 2 3 3 4 5]
[0. 0. 1. 1. 2. 2. 3. 3. 4. 5.]
[0. 0. 1. 1. 2. 2. 3. 3. 4. 5.]
[0. 0. 1. 1. 2. 2. 3. 3. 4. 5.]
[0. 0. 1. 1. 2. 2. 3. 3. 4. 5.]
[0. 0. 1. 1. 2. 2. 3. 3. 4. 5.]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [47]:
np.linspace(0,4,25).reshape((5,5))

array([[0.        , 0.16666667, 0.33333333, 0.5       , 0.66666667],
       [0.83333333, 1.        , 1.16666667, 1.33333333, 1.5       ],
       [1.66666667, 1.83333333, 2.        , 2.16666667, 2.33333333],
       [2.5       , 2.66666667, 2.83333333, 3.        , 3.16666667],
       [3.33333333, 3.5       , 3.66666667, 3.83333333, 4.        ]])

In [48]:
Z = np.zeros((5,5))
Z += np.arange(5)
print(Z)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


In [49]:
# without broadcasting
Z = np.tile(np.arange(0, 5), (5,1))
print(Z)

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [50]:
def generate():
    for x in range(10):
        yield x
Z = np.fromiter(generate(),dtype=int,count=-1)
print(Z)


[0 1 2 3 4 5 6 7 8 9]


#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [51]:
Z = np.linspace(0,1,11,endpoint=False)[1:]
print(Z)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


#### 40. Create a random vector of size 10 and sort it (★★☆)

In [52]:
z = np.random.random(10)
z.sort()
z

array([0.04768425, 0.17476492, 0.19900991, 0.23547172, 0.34880204,
       0.55746576, 0.7567455 , 0.77337051, 0.94937471, 0.97969904])

#### 41. How to sum a small array faster than np.sum? (★★☆)

In [53]:
from functools import reduce
total = reduce(
  lambda acc,val: acc + val,
  z,
  0
)
print(total)

# faster method
np.add.reduce(Z)

5.022388357981339


5.0

#### 42. Consider two random array A and B, check if they are equal (★★☆)

In [54]:
A = np.arange(9,-1,-1)
B = np.arange(10)
print(A,B)
print(np.array_equal(A,B))
print(np.allclose(A,B))
B = np.zeros(11)
print(np.array_equal(A,B))
# print(np.allclose(A,B)) # will raise error as they have different size

[9 8 7 6 5 4 3 2 1 0] [0 1 2 3 4 5 6 7 8 9]
False
False
False


#### 43. Make an array immutable (read-only) (★★☆)

In [55]:
Z = np.zeros(10)
Z.flags.writeable = False
Z[0] = 1

ValueError: assignment destination is read-only

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

In [56]:
Z = np.random.random((10,2))
print('Z',Z)
X,Y = Z[:,0], Z[:,1]
R = np.sqrt(X**2+Y**2)
T = np.arctan2(Y,X)
print('R',R)
print('T',T)

Z [[0.20775144 0.00540638]
 [0.01319079 0.80371221]
 [0.88946794 0.42009473]
 [0.94924575 0.63670052]
 [0.44321959 0.61348755]
 [0.3904704  0.10417675]
 [0.10181646 0.89585696]
 [0.09517954 0.96273859]
 [0.92732671 0.14063197]
 [0.44692424 0.19300748]]
R [0.20782177 0.80382045 0.98368328 1.14300265 0.7568425  0.40412861
 0.90162425 0.96743204 0.93792973 0.48681943]
T [0.02601742 1.55438547 0.44124217 0.59081979 0.94515571 0.26072506
 1.45762933 1.47225322 0.15050628 0.40766444]


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [57]:
Z = np.random.random(10)
Z[Z.argmax()] = -1
Z

array([ 0.45384276,  0.23764366,  0.93300871,  0.45723155,  0.60803842,
        0.77266163, -1.        ,  0.36450442,  0.7456001 ,  0.26739043])

#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

In [58]:
Z = np.zeros((5,5), [('x',float),('y',float)])
Z['x'], Z['y'] = np.meshgrid(np.linspace(0,1,5),
                             np.linspace(0,1,5))
print(Z)

[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) (★★☆)

#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

#### 49. How to print all the values of an array? (★★☆)

In [59]:
Z = np.zeros((40,40))
print(Z)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [60]:
np.set_printoptions(threshold=float("inf"))
Z = np.zeros((40,40))
print(Z)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

In [65]:
Z = np.arange(100)
v = np.random.uniform(0,100)
index = (np.abs(Z-v)).argmin()
print(Z,v)
print(Z[index])

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99] 94.13402878415124
94


#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

In [66]:
Z = np.zeros(10, [ ('position', [ ('x', float, 1),
                                  ('y', float, 1)]),
                   ('color',    [ ('r', float, 1),
                                  ('g', float, 1),
                                  ('b', float, 1)])])
print(Z)

[((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))]


C:\Users\prashant\AppData\Local\Temp\ipykernel_10276\274409719.py:1: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  Z = np.zeros(10, [ ('position', [ ('x', float, 1),


#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

In [75]:
Z = np.random.random((10,2))
X,Y = np.atleast_2d(Z[:,0], Z[:,1])
D = np.sqrt( (X-X.T)**2 + (Y-Y.T)**2)
print(D)
print(X,Y)

[[0.         0.84583144 0.17801318 0.31865771 0.17381944 0.39025187
  0.46603868 0.67499536 0.18866448 0.60328892]
 [0.84583144 0.         0.88118784 0.62577792 1.01956918 0.61219071
  0.38004049 0.74600014 0.71412496 0.2502886 ]
 [0.17801318 0.88118784 0.         0.26945812 0.24071175 0.53486611
  0.51132406 0.54620806 0.16857518 0.63090879]
 [0.31865771 0.62577792 0.26945812 0.         0.47054424 0.45706937
  0.28360086 0.38955878 0.1306478  0.37792557]
 [0.17381944 1.01956918 0.24071175 0.47054424 0.         0.52982722
  0.63984929 0.78657757 0.34170519 0.77691987]
 [0.39025187 0.61219071 0.53486611 0.45706937 0.52982722 0.
  0.32129956 0.83159815 0.41114686 0.43936087]
 [0.46603868 0.38004049 0.51132406 0.28360086 0.63984929 0.32129956
  0.         0.5680733  0.34276057 0.14146727]
 [0.67499536 0.74600014 0.54620806 0.38955878 0.78657757 0.83159815
  0.5680733  0.         0.49698339 0.56884437]
 [0.18866448 0.71412496 0.16857518 0.1306478  0.34170519 0.41114686
  0.34276057 0.49698

In [77]:
# Much faster with scipy
import scipy
# Thanks Gavin Heverly-Coulson (#issue 1)
import scipy.spatial

Z = np.random.random((10,2))
D = scipy.spatial.distance.cdist(Z,Z)
print(D)

[[0.         0.33709353 0.81804918 0.12115533 0.72952203 0.26283047
  0.61881101 0.6766704  0.90078491 0.93195301]
 [0.33709353 0.         0.79018126 0.33528556 0.87170816 0.35671433
  0.78933857 0.57593247 0.68103537 0.79408765]
 [0.81804918 0.79018126 0.         0.6975425  0.41088094 0.55535952
  0.46499928 0.24041736 0.49065447 0.28670128]
 [0.12115533 0.33528556 0.6975425  0.         0.62144199 0.14335057
  0.51604064 0.56477772 0.80904874 0.82161287]
 [0.72952203 0.87170816 0.41088094 0.62144199 0.         0.52424379
  0.12137457 0.54170283 0.86220423 0.69350339]
 [0.26283047 0.35671433 0.55535952 0.14335057 0.52424379 0.
  0.4341493  0.42550171 0.68947559 0.68278875]
 [0.61881101 0.78933857 0.46499928 0.51604064 0.12137457 0.4341493
  0.         0.54352181 0.87177274 0.73229123]
 [0.6766704  0.57593247 0.24041736 0.56477772 0.54170283 0.42550171
  0.54352181 0.         0.3285876  0.25728746]
 [0.90078491 0.68103537 0.49065447 0.80904874 0.86220423 0.68947559
  0.87177274 0.328587

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

In [78]:
Z = (np.random.rand(10)*100).astype(np.float32)
Y = Z.view(np.int32)
Y[:] = Z
print(Z,Y)

[8.41e-45 1.25e-43 8.27e-44 8.27e-44 1.06e-43 1.16e-43 1.19e-43 6.03e-44
 9.39e-44 8.27e-44] [ 6 89 59 59 76 83 85 43 67 59]


#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

#### 56. Generate a generic 2D Gaussian-like array (★★☆)

#### 57. How to randomly place p elements in a 2D array? (★★☆)

#### 58. Subtract the mean of each row of a matrix (★★☆)

#### 59. How to sort an array by the nth column? (★★☆)

#### 60. How to tell if a given 2D array has null columns? (★★☆)

#### 61. Find the nearest value from a given value in an array (★★☆)

#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

#### 63. Create an array class that has a name attribute (★★☆)

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

#### 69. How to get the diagonal of a dot product? (★★★)

#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

#### 72. How to swap two rows of an array? (★★★)

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

#### 75. How to compute averages using a sliding window over an array? (★★★)

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

#### 82. Compute a matrix rank (★★★)

#### 83. How to find the most frequent value in an array?

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

#### 86. Consider a set of p matrices with shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★)

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

#### 91. How to create a record array from a regular array? (★★★)

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

#### 95. Convert a vector of ints into a matrix binary representation (★★★)

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)